service: apiCars

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    CLIENT_ID:
      Ref: MyCognitoPoolClient
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt Cars.Arn
  endpointType: REGIONAL
  apiName: apiCars-${self:provider.stage}
  apiKeys:
    - apiKeyCars-${self:provider.stage}
  usagePlan:
    quota:
      limit: 1000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 200
      rateLimit: 100
functions:
  list:
    handler: cars/list.handler
    events:
      - http:
          path: cars
          method: get
          private: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref MyAuthorizer
  get:
    handler: cars/get.handler
    events:
      - http:
          path: cars/{id}
          method: get
          private: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref MyAuthorizer
  create:
    handler: cars/create.handler
    events:
      - http:
          path: cars
          method: put
          private: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref MyAuthorizer
  edit:
    handler: cars/edit.handler
    events:
      - http:
          path: cars/{id}
          method: post
          private: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref MyAuthorizer
  delete:
    handler: cars/delete.handler
    events:
      - http:
          path: cars
          method: delete
          private: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref MyAuthorizer
  login:
    handler: auth/login.handler
    events:
      - http:
          path: login
          method: post
          private: true
          cors: true
  signup:
    handler: auth/signup.handler
    events:
      - http:
          path: signup
          method: post
          private: true
          cors: true
  confirmsignup:
    handler: auth/confirmsignup.handler
    events:
      - http:
          path: confirmsignup
          method: post
          private: true
          cors: true
resources:
  - ${file(resources/dynamodb_serverless.yml)}
  - ${file(resources/cognito_serverless.yml)}
  - ${file(resources/apigateway_serverless.yml)}
